config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.order("priority DESC").all
    if Todo.count > 0
      @percent = ((Todo.where(complete: true).count.to_f / Todo.count.to_f) * 100).to_i
    else
      @percent = 0
    end
    @percent1 = Todo.where(complete: true).count
    @percent2 = Todo.where(complete: false).count
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path(@todo)
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)

      redirect_to todos_path(@todo)
    else
      render :edit
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path(@todo)
  end

  private
  def todo_params
    params.require(:todo).permit(:item, :complete, :details, :priority)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :item %>:
  <%= f.text_field :item %>
  <br>
  <%= f.label :details %>:
  <%= f.text_area :details %>
  <br>
  <%= f.label :priority %>:
  <%= f.radio_button :priority, 1 %> Low
  <%= f.radio_button :priority, 2 %> Normal
  <%= f.radio_button :priority, 3 %> High

  <br>
  <%= f.label :complete %>:
  <%= f.check_box :complete %>
  <br>
  <%= f.submit 'Add Item' %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit: <%= @todo.item %></h1>

<%= render(partial: 'form') %>
<br>
<br>
<%= link_to 'Cancel', todos_path %>

app/views/todos/index.html.erb
<h1>Todo list - <%= @percent %>% Complete</h1>


<hr>
<h3><%= @percent2 %> Incomplete:</h3>
<br>
<p>
  Color Legend:
  <span style="color: red">High Priority</span> -
  <span style="color: green">Normal Priority</span> -
  <span style="color: blue">Low Priority</span>
</p>
<br>
<ol>
  <% @todos.each do |todo| %>
    <% if todo.complete == false %>
    <li>
    <% case todo.priority %>
      <% when 1 %>
      <span style='color: blue'><%= todo.item %></span>
      <% when 2 %>
      <span style='color: green'><%= todo.item %></span>
      <% when 3 %>
      <span style='color: red'><%= todo.item %></span>
      <% end %>
       -- <%= link_to 'See Details', todo_path(todo)%> |
      <%= link_to 'Edit', edit_todo_path(todo)%> |
      <%= link_to 'Delete', todo_path(todo), method: :delete, data: {confirm: 'Do you want to delete this item?'} %>
    </li>
    <% end %>
  <% end %>
</ol>
<br>
<%= link_to 'New Item', new_todo_path %>
<hr>
<h3><%= @percent1 %> Completed:</h3>
<ol>
  <% @todos.each do |todo| %>
    <% if todo.complete == true %>
    <li>
      <strike><%= todo.item %></strike>
       -- <%= link_to 'See Details', todo_path(todo)%> |
      <%= link_to 'Edit', edit_todo_path(todo)%> |
      <%= link_to 'Delete', todo_path(todo), method: :delete, data: {confirm: 'Do you want to delete this item?'} %>
    </li>
    <% end %>
  <% end %>
</ol>

app/views/todos/new.html.erb
<h1>Add Item to TODO list</h1>
<hr>
<%= render(partial: 'form') %>

app/views/todos/show.html.erb
<h1>Item Details</h1>
<hr>

<h3>Item: <i><%= @todo.item %></i></h3>

  <h4>
    Priority:
     <% case @todo.priority %>
        <% when 1 %>
          <i> Low </i>
        <% when 2 %>
          <i> Normal </i>
        <% when 3 %>
          <i> High </i>
      <% end %>
  </h4>


<h4>
Details: <i><%= @todo.details %></i>
</h4>

<h5>
  Completed: <%= @todo.complete ? 'Yes' : 'No' %>
</h5>